package com.bt.om.mapper;

import com.bt.om.entity.DrawCash;

public interface DrawCashMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table draw_cash
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table draw_cash
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	int insert(DrawCash record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table draw_cash
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	int insertSelective(DrawCash record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table draw_cash
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	DrawCash selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table draw_cash
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	int updateByPrimaryKeySelective(DrawCash record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table draw_cash
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	int updateByPrimaryKey(DrawCash record);
}